import 'package:drift/drift.dart';
import 'package:field_service/core/database/tables/customers_table.dart';
import 'package:field_service/core/database/tables/job_events_table.dart';
import 'package:field_service/core/database/tables/job_files_table.dart';
import 'package:field_service/core/database/tables/jobs_table.dart';
import 'package:field_service/core/database/tables/sync_queue_table.dart';

part 'app_database.g.dart';

/// The application's local Drift database.
///
/// Architectural rule (unchanged from [AppDatabaseFactory]): Drift is an
/// implementation detail of the **Data** layer. Only data sources, the sync
/// engine and repository implementations may touch this class; the Domain
/// layer never sees a database type.
///
/// The database is the **source of truth for the UI** in the offline-first
/// design: screens read local rows, repositories write locally and enqueue
/// the change on the sync queue, and the sync engine pushes it when the
/// internet is available.
@DriftDatabase(
  tables: <Type>[
    SyncQueueTable,
    CustomersTable,
    JobsTable,
    JobEventsTable,
    JobFilesTable,
  ],
)
class AppDatabase extends _$AppDatabase {
  /// Opens the database on any drift [QueryExecutor] (production:
  /// `AppDatabaseFactory().open()`; unit tests: an in-memory database).
  AppDatabase(super.executor);

  /// Current schema version. Bump it and extend [migration] for every
  /// schema change — the database is never deleted or recreated on upgrade.
  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
      // Query support for the hot paths of the sync engine.
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_sync_queue_status_created '
        'ON sync_queue (status, created_at)',
      );
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_sync_queue_entity '
        'ON sync_queue (entity_type, entity_id)',
      );
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_customers_sync_status '
        'ON customers (sync_status, local_updated_at)',
      );
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_jobs_sync_status '
        'ON jobs (sync_status, local_updated_at)',
      );
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_jobs_assigned_employee '
        'ON jobs (assigned_employee_id)',
      );
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_job_events_job '
        'ON job_events (job_id, created_at)',
      );
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_job_files_job '
        'ON job_files (job_id)',
      );
      await m.database.customStatement(
        'CREATE INDEX IF NOT EXISTS idx_job_files_sync_status '
        'ON job_files (sync_status)',
      );
    },
    onUpgrade: (Migrator m, int from, int to) async {
      // Future schema versions land here, oldest first:
      //
      //   if (from < 2) { await tables.addColumn(...); }
      //
      // Rule: upgrades only add/extend. Dropping tables or recreating the
      // database is forbidden — a technician's offline work must survive
      // every app update.
    },
  );

  // Note: typed access to the tables (`syncQueueTable`, `customersTable`,
  // `jobsTable`, `jobEventsTable`, `jobFilesTable`) is generated by drift on
  // `_$AppDatabase` and inherited by this class.
}
